modLoader = "javafml"
loaderVersion = "${loader_version_range}"
license = "${mod_license}"

mixinConfigs = [
    "vs_logistics.mixins.json",
    "createaddition.mixins.json"
]

[[mods]]
modId = "${mod_id}"
version = "${mod_version}"
displayName = "${mod_name}"
authors = "${mod_authors}"
description = '''${mod_description}'''

[[dependencies."${mod_id}"]]
modId = "forge"
mandatory = true
versionRange = "${forge_version_range}"
ordering = "NONE"
side = "BOTH"

[[dependencies."${mod_id}"]]
modId = "minecraft"
mandatory = true
versionRange = "${minecraft_version_range}"
ordering = "NONE"
side = "BOTH"

[[dependencies."${mod_id}"]]
modId = "create"
mandatory = true
versionRange = "[6.0.7,)"
ordering = "NONE"
side = "BOTH"

[[dependencies."${mod_id}"]]
modId = "createaddition"
mandatory = false
versionRange = "any"
ordering = "AFTER"
side = "BOTH"
